### ISSUE TITLE
Incompatible with django 1.11

### ISSUE THREAD

**Issue by serkanaltuntas** [kalwalkden/django-materializecss-form#15]
Django version: 1.11.6
django-materializecss-form: 1.0.1

Request Method: | GET
-- | --
1.11.6
TypeError
context must be a dict rather than Context.
/data/lib/python3.6/site-packages/django/template/context.py in make_context, line 287
/data/bin/python3.6
3.6.2
['/app',  '/data/bin',  '/data/lib/python36.zip',  '/data/lib/python3.6',  '/data/lib/python3.6/lib-dynload',  '/data/lib/python3.6/site-packages']
Fri, 17 Nov 2017 14:29:28 +0000

**Comment by Allan-Nava** [comment]
Is still alive the project ? I used django 1.11.5 it works?

**Comment by florent1933** [comment]
Hey Allan,

I don't know if it works with this version of Django.

This repo is not maintained.

Best regards,

Florent


Le lun. 12 mars 2018 à 10:34, Allan Nava <notifications@github.com> a
écrit :

**Comment by Allan-Nava** [comment]
Con you try?

Inviato da iPhone

**Comment by phoebebright** [comment]
Pulling latest version from github works in django 2.

**Comment by kalwalkden** [comment]
This repo is now maintained again. The latest version has been confirmed and tested to work with Django 1.11.
