### ISSUE TITLE
Textarea don't receive the class 'invalid'

### ISSUE THREAD

**Issue by gabrielbiasi** [kalwalkden/django-materializecss-form#2]
Example:
![image](https://cloud.githubusercontent.com/assets/9423868/8840628/fd3b68e0-30b1-11e5-9605-239e1c726f34.png)

The textarea don't receive the class 'invalid' on submit form with error.

**Comment by florent1933** [comment]
Hi @gabrielbiasi, is it working? Sorry, I don't have time to maintain this repo.

But you can make a PR, and I will be happy to merge it.
