### ISSUE TITLE
Issue with date inputs and default browser datepickers

### ISSUE THREAD

**Issue by dwjorgeb** [kalwalkden/django-materializecss-form#29]
Whenever there's a input with type of ```date```, ```time``` or ```datetime-local``` the browser (especially Firefox) tries to show the default datepicker and this happens:

![date](https://user-images.githubusercontent.com/13308197/50162603-acfc8d00-02d6-11e9-852b-c18430312b91.PNG)

You should maybe change the type to text, as per the Materialize documentation

**Comment by FlorianFusseder** [comment]
I still have this problem in firefox with version 1.1.17. The tag v1.1.17 does not contain the fix...
Furthermore this happens:

![image](https://user-images.githubusercontent.com/22769455/84935992-dc61a500-b0d9-11ea-901f-bcc922639843.png)
