### ISSUE TITLE
Any plan to integrate Materialize Stepper?

### ISSUE THREAD

**Issue by nittolese** [kalwalkden/django-materializecss-form#37]
Hi guys,
your addon really save me hours of time when working with forms.

I have a question for you: do you plan to integrate [Materialize Stepper ](https://kinark.github.io/Materialize-stepper/) in django-materializecss ? 

I'm struggling in trying to make this work on my Django project, trying to use django-formtools for wizard form, but I have no luck with this.

Thank you!

**Comment by kalwalkden** [comment]
@nittolese 

I hadn't planned on adding this. However, it should be possible. Would you like to try creating it yourself and putting in the pull request?
