### ISSUE TITLE
BUG: Checkboxes appear double

### ISSUE THREAD

**Issue by creyD** [kalwalkden/django-materializecss-form#38]
The rest of the labels and input fields show up fine, but the checkboxes double in every browser I tested so far (Safari, Chrome, Firefox). Using the latest version of iQuery, materializecss, Django, Python and MacOS.

Thank you for your help and keep up the good work!

Screenshot below shows output:
<img width="143" alt="Screenshot 2019-05-15 at 13 13 31" src="https://user-images.githubusercontent.com/15138480/57771601-7145e200-7713-11e9-91ad-0e999a6ec997.png">

**Comment by creyD** [comment]
@kalwalkden Any idea why that happens? Thank you!

**Comment by kalwalkden** [comment]
@creyD This usually is a django-materializecss-form issue, but an issue with calling the initialization Javascript twice within your code. Where you able to resolve this?

**Comment by creyD** [comment]
Nope, as I couldn't resolve it, I didn't use it any longer and manually adjusted the styling...

**Comment by creyD** [comment]
When you fix this, you can let me know if you want, I'll give it another try :)

**Comment by creyD** [comment]
It stopped happening, I believe it was either a connection problem or was fixed during an update of any of the components. Not to sure what happend, but I can't reproduce it anymore.
