### ISSUE TITLE
Problem with pip installation

### ISSUE THREAD

**Issue by saemideluxe** [kalwalkden/django-materializecss-form#44]
Firstly, thanks for merging commits and updating the pip package.
There seems to be an issue with the installation path of the package. After I run ```pip install django-materializecss-form``` I found the following path structure: ```.venv/lib/python3.7/site-packages/templatetags/materializecss.py```. Note the missing materializecss package name. This should be ```.venv/lib/python3.7/site-packages/materializecss/templatetags/materializecss.py```, right?

I am no expert with distutils, but I think removing the package_dir line in setup.py would be sufficient.
```package_dir={"": "materializecssform"},```

:+1: for using black

**Comment by saemideluxe** [comment]
The following works for me:
- Removing package_dir
- changing ```PACKAGES = find_packages(where="materializecssform")``` to ```PACKAGES = find_packages(where="")```

**Comment by kalwalkden** [comment]
Thank you @saemideluxe I created a new release - v1.1.16

**Comment by saemideluxe** [comment]
Sorry, my previous comment was incorrect. You also need to remove the where parameter from find_packages, otherwise no files will be included in the package distribution. It first worked for me because I installed it with ```pip install -e /path/to/pippackage``` to test which does not copy any files.

It should look like this:
```PACKAGES = find_packages()```

Also we need to add ``include_package_data=True,``` as a parameter to the setup function in setup.py in order to add the *.html files.

That should fix things. Could make a new release with these changes?

**Comment by saemideluxe** [comment]
Hmm.. And I just saw that the template files are missing too. Let check this before you make a new release.
