### ISSUE TITLE
Still an issue with pip installation

### ISSUE THREAD

**Issue by gakhov** [kalwalkden/django-materializecss-form#46]
It seems that the issue of https://github.com/kalwalkden/django-materializecss-form/issues/44 is not resolved properly. The module incorrectly installed with `pip` and cannot be found in python.

How to reproduce:
------------------------

1. Create a fresh virtual environment, e.g.

```
mkdir /tmp/dmf
cd /tmp/dmf
virtualenv . -p python3
```

2. Install `django-materializecss-form` (1.1.15, 1.1.16 and the master have the same issue)

```
bin/pip install django-materializecss-form==1.1.16
```

3. Test it is missing in python

```
bin/python -c "import materializecssform"
```

4. Result

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'materializecssform'
```

Note
-------

The module is also missing from `bin/python -c "help('modules')` and cannot be found when mentioned in Django's `INSTALLED_APPS`.

This issue appears after 1.1.15 release (version 1.1.14 is fine) and probably related to the same commit as https://github.com/kalwalkden/django-materializecss-form/issues/44

**Comment by kalwalkden** [comment]
I have added @saemideluxe to this repository as an owner. Hopefully, they will have some time to look into this issue.

**Comment by saemideluxe** [comment]
This is fixed with #45. Will deploy to pip as soon as possible.

**Comment by saemideluxe** [comment]
Okay, we updated the package on pypi. If you do a fresh download (you might need to use ```pip install --upgrade ...```) it should install correctly.

**Comment by gakhov** [comment]
Thank you! I can confirm that in `1.1.17` the issue has been fixed.
