### ISSUE TITLE
ModelChoiceField prefetch_related error with django 1.8.6

### ISSUE THREAD

**Issue by iraycd** [kalwalkden/django-materializecss-form#5]
The error is mostly related to
https://code.djangoproject.com/ticket/25496

Which is the an update of 1.8.6:

https://docs.djangoproject.com/en/1.8/releases/1.8.6/

**Comment by kalwalkden** [comment]
This repo is now maintained again. The latest version has been confirmed and tested to work with Django 1.11.

**Comment by kalwalkden** [comment]
This is an old, expired issue.
