### ISSUE TITLE
Issue with date inputs and default browser datepickers

### ISSUE THREAD

**Issue by FlorianFusseder** [kalwalkden/django-materializecss-form#53]
Hello, 
as i already commented in #29 this is not fixed in the latest release, although it should have merged. At least that i what i can see..

**Comment by SoarinFerret** [comment]
I also noticed this - when I wrote the patch, I had already manually updated my internal build pipeline to just use my patched version before it was merged. I was going through and updating all my dependencies for the project and saw this came back up again.

@kalwalkden @saemideluxe Any way we can get a new point release with the latest merges in there? Thanks in advance!

**Comment by krewsayder** [comment]
Any updates to when this will be fixed?  Love this library, would appreciate the main download to have fixed datepickers.

**Comment by saemideluxe** [comment]
I pushed a new release, 1.1.18, from master. Can you confirm everything works as desired? @kalwalkden will need to approve the new version in the code, but the pip-package should be ready to use

**Comment by XimmersiveX** [comment]
I can still only download 1.1.17

**Comment by adam-of-barot** [comment]
@saemideluxe, @XimmersiveX
The pypi version of 1.1.18 is missing both a setup.py and a pyproject.toml, so pip can't install it. Installing it from the github repo with pip works.
The version on master is still out of date, but the one on the saemideluxe-patch-1 branch should be good.
